swagger: "2.0"
info:
  description: "This is the REST API definition for school management app by Group B - MSC IT Batch 15 ICBT"
  version: "1.0.0"
  title: "School Management"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:3000"
basePath: "/api"
tags:
  - name: "admin"
    description: "Operations about admin"
schemes:
  - "https"
  - "http"
paths:
  /admin/login:
    post:
      tags:
        - "user"
      summary: "Logs admin into the system"
      description: ""
      operationId: "loginUser"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - name: "adminID"
          in: "body"
          description: "The user name for login"
          required: true
        - name: "password"
          in: "body"
          description: "The password for login in clear text"
          required: true
          type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "string"
          headers:
            X-Rate-Limit:
              type: "integer"
              format: "int32"
              description: "calls per hour allowed by the user"
            X-Expires-After:
              type: "string"
              format: "date-time"
              description: "date in UTC when token expires"
        400:
          description: "Invalid username/password supplied"

securityDefinitions:
  petstore_auth:
    type: "oauth2"
    authorizationUrl: "http://petstore.swagger.io/oauth/dialog"
    flow: "implicit"
    scopes:
      write:pets: "modify pets in your account"
      read:pets: "read your pets"
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
definitions:
  Admin:
    type: "object"
    required:
      - adminID
      - userType
    properties:
      adminID:
        type: "string"
      name:
        type: "string"
      email:
        type: "string"
      password:
        type: "string"
      userType:
        type: "string"
    xml:
      name: "User"
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"